config/routes.rb
Neo4jTestApp::Application.routes.draw do
  resources :articles

  root :to => "welcome#index"
  resources :users do 
    get "confirm", :on => :member
  end

  get "signup" => "users#signup", :as => "signup"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  post "log_in" => "sessions#create", :as => "connect"

end

app/models/user.rb
class User < Neo4j::Rails::Model
  #property :username, :type => String
  #property :email, :type => String
  property :password_hash, :type => String
  property :password_salt, :type => String
  property :pending_account, :type => String

  # add an exact lucene index on the email property
  property :email, :index => :exact, :unique => true
  property :username, :index => :exact, :unique => true

  def to_param
    username.parameterize
  end

  has_n(:articles).to(Article, :rates).relationship(Rate)
  has_n(:articles).to(Article, :writes).relationship(Write)

  before_save  :encrypt_password
  #after_create :set_pending

  attr_accessor :password, :login
  attr_accessible :email, :username, :password, :login, :pending_account

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  username_regex = /\A[\w+\-.]/i  

  validates :email, :presence => true, :format   => { :with => email_regex }
  validates :email, :uniqueness => true #, :unless => :pending_account?
  validates :username, :presence => true, :format   => { :with => username_regex }
  validates :username, :uniqueness => true #, :unless => :pending_account?
  validates :password, :presence   => true, :on => :create
  validates :password, :length     => { :within => 4..42 }, :on => :create
  #accepts_nested_attributes_for :avatar, :allow_destroy => true


  def pending_account?
  	pending_account
  end
  def confirm_user
  	self.pending_account = Time.now.strftime("%H:%M %d/%m/%y").to_s unless pending_account?
  end
  def confirm_user!
  	confirm_user
  	save 
  end
  def set_pending
  	pending_account = nil
  end
  def encrypt_password
    #if old_password.present? 
    #  if self.password_hash != BCrypt::Engine.hash_secret(old_password, self.password_salt)        
    #    return false
    #  end
    #end
	if password.present?
		#@old_salt = self.password_salt
		self.password_salt = BCrypt::Engine.generate_salt
		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	end
  end
  def self.find_login(thing)
 		if thing && thing.include?("@")
 			user=User.where("email like ?",thing.downcase).first
 		elsif thing
 			user=User.find_by_username(thing)
 		end
 		user
 	end
  def self.authenticate(login, password)
 		user = User.find_login(login)
 		
 		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
 			return user
 		elsif user # this is for users who created or want to login from a smartphone -> starts with capital 
 			pass = password.capitalize
 			pass2 = password[0,1].downcase.to_s + password[1, password.length].to_s
 			if user.password_hash == BCrypt::Engine.hash_secret(pass, user.password_salt) || user.password_hash == BCrypt::Engine.hash_secret(pass2, user.password_salt)
 				return user
 			else
 				return nil
 			end
 		else
 			nil
 		end
 	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by_username(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end
  def signup
    @user = User.new
    respond_to do |format|
      format.html { render "users/new" }
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  #get
  def confirm
    @user = User.find_by_username(params[:id])
    respond_to do |format|
      if @user.confirm_user!
        format.html { redirect_to @user, :notice => 'User was successfully confirmed.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        raise @user.errors.messages.to_s
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end


  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :class => "form-signin" do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= f.text_field :username, :placeholder => "Username" %>
  </div>
  <div class="field">
    <%= f.text_field :email, :placeholder => "email#blog.me" %>
  </div>
  <div class="field">

    <%= f.password_field :password, :placeholder => "password" %>
  </div>
  
  <div class="actions">
    <%= f.submit "Create account", :class => "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table table-striped table-bordered">
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Pending account</th>
    <th>State</th>
    <th>See this</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= user.pending_account %></td>
    <td>
        <% unless user.pending_account? %>
            <%= link_to "Activate", confirm_user_path(user) %>
        <% else %>
            Activated
        <% end %>
    </td>
    <td>
        <%= link_to 'Show', user %>
        <% link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
    </td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="login_form">
	<h1>New user</h1>

	<%= render 'form' %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password hash:</b>
  <%= @user.password_hash %>
</p>

<p>
  <b>Password salt:</b>
  <%= @user.password_salt %>
</p>

<p>
  <b>Pending account:</b>
  <%= @user.pending_account %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>