config/routes.rb
Neo4jTestApp::Application.routes.draw do
  resources :articles

  root :to => "welcome#index"
  resources :users do 
    get "confirm", :on => :member
  end

  get "signup" => "users#signup", :as => "signup"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  post "log_in" => "sessions#create", :as => "connect"

end

app/views/layouts/_header.html.erb
<div id="user-nav" class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<div class="nav-collapse collapse">	
			  	<ul class="nav nav-pills pull-right">
					<% if current_user %>
						<li>
							<%= link_to current_user do %> 
								<i class="icon-user"></i> 
								<%= current_user.username %> 
							<% end %>  
						</li>  	 	  	
						<li>
							<%= link_to root_path do %> 
								<i class="icon-home"></i> 
								Home
							<% end %>  
						</li>  
						<li>
							<%= link_to logout_path do %>  
								<i class="icon-off"></i> 
								Log out
							<% end %>
						</li>  
						<li>	
							<%= link_to "Users", users_path %>
						</li>  
					<% else %>
						<li>
							<%= link_to "Sign up", signup_path %> 
						</li>
						<li>
							<%= link_to "Log in", login_path %> 
						</li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
</div>	
	
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Me blogs too!</title>
  <meta http-equiv = "Content-Type" content = "text/html;charset=iso-8859-1">
  <meta name = "Me blogs too">
  <meta name = "keywords" content = "Blogs, <%= content_for?(:keywords) ? yield(:keywords) : "Tags" %>">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/css/bootstrap.min.css" rel="stylesheet">
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<div class="container">
	<div class="jumbotron subhead">
	  <h3 class="muted"> Me blogs too! </h3>
	</div>
	<hr />
	
	<%= yield %>
</div>

</body>
</html>